# Example configuration file for shemcp (MCP Shell Server)
# Copy this to ~/.config/shemcp/config.toml and customize as needed

config_version = 1  # Configuration format version (not the package version)

[server]
name = "shemcp"  # Server identity shown to MCP clients; version comes from package.json

[directories]
# Sandbox root is derived at runtime in the following order:
# 1) SHEMCP_ROOT or MCP_SANDBOX_ROOT environment variable (if set and exists)
# 2) Nearest Git repository root from process.cwd()
# 3) process.cwd() as a fallback
#
# Note: The TOML field below is currently ignored for sandbox selection; prefer
# environment variables for explicit overrides. This key is reserved for
# potential future static overrides.
# root = "/absolute/path"  # Deprecated/ignored; use SHEMCP_ROOT or MCP_SANDBOX_ROOT

[commands]
# Regular expressions for allowed commands (case insensitive)
allow = [
    "^git(\\s|$)",         # Git commands
    "^gh(\\s|$)",          # GitHub CLI
    "^make(\\s|$)",        # Make build tool
    "^npm(\\s|$)",         # Node package manager
    "^yarn(\\s|$)",        # Yarn package manager
    "^grep(\\s|$)",        # Search text
    "^find(\\s|$)",        # Find files
    "^ls(\\s|$)",          # List files
    "^pwd(\\s|$)",         # Print working directory
    "^echo(\\s|$)",        # Echo text
    "^cat(\\s|$)",         # Display file contents
    "^head(\\s|$)",        # Show file beginning
    "^tail(\\s|$)",        # Show file end
    "^curl(\\s|$)",        # HTTP client
    "^wget(\\s|$)",        # Web downloader
]

# Regular expressions for explicitly denied commands (checked after allow list)
deny = [
    "^git\\s+push\\s+(origin\\s+)?(main|master)(\\s+.*)?$",  # Prevent push to main/master
    "^rm\\s+-rf\\s+/",     # Prevent dangerous recursive deletes
    "^sudo(\\s|$)",        # No privilege escalation
    "^su(\\s|$)",          # No user switching
]

[limits]
# Maximum time per command (1-300 seconds)
timeout_seconds = 60

# Maximum output size per stream in bytes (1KB - 10MB)
max_output_bytes = 2000000

[environment]
# Environment variables to pass through to commands
whitelist = [
    "PATH",
    "HOME", 
    "USER",
    "LANG",
    "LC_ALL",
    "TERM",
    "SHELL"
]

[security]
# Whether to allow runtime policy changes via shell_set_policy tool
# (Currently informational; the tool is always available in this version.)
allow_runtime_policy_changes = true

# Whether to enforce secure file permissions on config files (600/644)
require_secure_permissions = false